/home/gsnearing/projects/SACSMA-SNOW17
Using 40 cores of 40 total.
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/gsnearing/anaconda3/envs/sacsma/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/home/gsnearing/anaconda3/envs/sacsma/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/gsnearing/anaconda3/envs/sacsma/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 593, in __call__
    return self.func(*args, **kwargs)
  File "/home/gsnearing/anaconda3/envs/sacsma/lib/python3.8/site-packages/joblib/parallel.py", line 252, in __call__
    return [func(*args, **kwargs)
  File "/home/gsnearing/anaconda3/envs/sacsma/lib/python3.8/site-packages/joblib/parallel.py", line 252, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/gsnearing/projects/SACSMA-SNOW17/optimize_single_basin.py", line 15, in run_single_basin
    obj_fun_dates = pd.DataFrame(list(chain.from_iterable(pd.date_range(sdi, edi) for sdi, edi in zip(sd, ed))), columns = ('train_dates',))
  File "/home/gsnearing/projects/SACSMA-SNOW17/optimize_single_basin.py", line 15, in <genexpr>
    obj_fun_dates = pd.DataFrame(list(chain.from_iterable(pd.date_range(sdi, edi) for sdi, edi in zip(sd, ed))), columns = ('train_dates',))
  File "/home/gsnearing/anaconda3/envs/sacsma/lib/python3.8/site-packages/pandas/core/indexes/datetimes.py", line 1172, in date_range
    dtarr = DatetimeArray._generate_range(
  File "/home/gsnearing/anaconda3/envs/sacsma/lib/python3.8/site-packages/pandas/core/arrays/datetimes.py", line 376, in _generate_range
    raise ValueError("Neither `start` nor `end` can be NaT")
ValueError: Neither `start` nor `end` can be NaT
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "batch_run_experiment.py", line 43, in <module>
    Parallel(n_jobs=use_n_cores)(delayed(run_basin)(basin, 
  File "/home/gsnearing/anaconda3/envs/sacsma/lib/python3.8/site-packages/joblib/parallel.py", line 1042, in __call__
    self.retrieve()
  File "/home/gsnearing/anaconda3/envs/sacsma/lib/python3.8/site-packages/joblib/parallel.py", line 921, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/gsnearing/anaconda3/envs/sacsma/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 540, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/gsnearing/anaconda3/envs/sacsma/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/gsnearing/anaconda3/envs/sacsma/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
ValueError: Neither `start` nor `end` can be NaT
